[workspace]
members = [
    "src/arcmindai_controller",
    "src/arcmindai_brain",
    "src/arcmindai_tools",
    "src/cycles_battery"
]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
