name: Deploy New Instance

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ARCMIND_CI_TOKEN }}
          submodules: true
      - uses: Swatinem/rust-cache@v2
      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup target add wasm32-unknown-unknown
      - name: Install DFX
        run: echo y | sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
        env:
          DFX_VERSION: 0.15.2
      - name: Fetch git submodule arcmindvector
        run: git submodule update --init --recursive
      - name: Add DFX identity and wallets
        run: ./scripts/add-ic-identity.sh
        env:
          DFX_IDENTITY: ${{ secrets.DFX_IDENTITY_PROD }}
          DFX_WALLETS: ${{ secrets.DFX_WALLETS_PROD }}
      - name: Provision a new suite of ArcMind Canisters to IC mainnet
        id: provision
        run: scripts/provision.sh
        env:
          IC_NETWORK: ic
          OWNER_PRINCIPAL: ${{ secrets.OWNER_PRINCIPAL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_SEARCH_ENGINE_ID: ${{ secrets.GOOGLE_SEARCH_ENGINE_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BEAMFI_PRINCIPAL: ${{ secrets.BEAMFI_PRINCIPAL }}
          BILLING_KEY: ${{ secrets.BILLING_KEY }}
      - name: Debug URL
        run: echo https://completedeploy-4gbndkvjta-uc.a.run.app?apiKey=${{ secrets.FB_API_KEY }}&canisterId=${{ steps.provision.outputs.controller_principal }}
      - name: Call Firebase Function /complete_deploy and assert HTTP status 200
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://completedeploy-4gbndkvjta-uc.a.run.app?apiKey=${{ secrets.FB_API_KEY }}&canisterId=${{ steps.provision.outputs.controller_principal }}
          method: 'GET'
